"""Synthesising the 2021 England and Wales Census with public data."""


from .api import CensusAPI

__version__ = "0.0.1"

POPULATION_TYPES = ("HH", "HRP", "UR")

AREA_TYPES = (
    "nat",
    "ctry",
    "rgn",
    "lep",
    "nhser",
    "lhb",
    "icb",
    "sicb1",
    "utla23",
    "utla",
    "ltla23",
    "ltla",
    "senc",
    "wpc",
    "wd",
    "msoa",
    "lsoa",
    "oa",
)

DIMENSIONS_BY_POPULATION_TYPE = {
    "HH": (
        "accommodation_type",
        "accom_by_dwelling_type",
        "heating_type",
        "hh_adults_and_children_11a",
        "hh_adults_disabled_4a",
        "hh_adults_employment_5a",
        "hh_adults_num_3a",
        "hh_adult_welsh_speakers",
        "hh_away_student_4a",
        "hh_carers_6a",
        "hh_dependent_children_3a",
        "hh_deprivation",
        "hh_deprivation_education",
        "hh_deprivation_employment",
        "hh_deprivation_health",
        "hh_deprivation_housing",
        "hh_disabled_4a",
        "hh_families_count",
        "hh_families_type_12a",
        "hh_family_composition_37a",
        "hh_hrp_veteran",
        "hh_language",
        "hh_lifestage_13a",
        "hh_multi_ethnic_combination_8a",
        "hh_multi_ethnic_group",
        "hh_multi_language",
        "hh_multi_religion",
        "hh_multi_religion_combination",
        "hh_not_limited_4a",
        "hh_no_condition_4a",
    ),
    "HRP": (
        "accommodation_type",
        "accom_by_dwelling_type",
        "activity_last_week",
        "age_arrival_uk_8a",
        "alternative_address_indicator",
        "country_of_birth_60a",
        "disability",
        "economic_activity_status_12a",
        "english_proficiency",
        "ethnic_group_tb_20b",
        "has_ever_worked",
        "health_in_general",
        "hh_adults_and_children_11a",
        "hh_adults_disabled_4a",
        "hh_adults_employment_5a",
        "hh_adults_num_3a",
        "hh_adult_welsh_speakers",
        "hh_away_student_4a",
        "hh_carers_6a",
        "hh_dependent_children_3a",
        "hh_deprivation",
        "hh_deprivation_education",
        "hh_deprivation_employment",
        "hh_deprivation_health",
        "hh_deprivation_housing",
        "hh_disabled_4a",
        "hh_families_count",
        "hh_families_type_12a",
        "hh_family_composition_37a",
        "hh_language",
    ),
    "UR": (
        "activity_last_week",
        "age_arrival_uk_23a",
        "alternative_address_indicator",
        "country_of_birth_190a",
        "country_of_birth_60a",
        "disability",
        "economic_activity_status_12a",
        "english_proficiency",
        "ethnic_group_tb_20b",
        "has_ever_worked",
        "health_in_general",
        "highest_qualification",
        "hours_per_week_worked",
        "industry_current_88a",
        "industry_former_17a",
        "is_carer",
        "legal_partnership_status",
        "living_arrangements_11a",
        "main_language_23a",
        "main_language_detailed_26a",
        "migrant_ind",
        "multi_passports",
        "national_identity_all",
        "national_identity_detailed",
        "ns_sec",
        "occupation_current_105a",
        "occupation_former",
        "passports_all_52a",
        "place_of_work_ind",
        "religion_tb",
    ),
}

__all__ = [
    "AREA_TYPES",
    "CensusAPI",
    "DIMENSIONS_BY_POPULATION_TYPE",
    "POPULATION_TYPES",
    "__version__",
]
